name: 'Semantic Version Tag'
description: 'Create semantic version tags with automatic pre-release detection'
author: 'Ananta Kumar Ghosh'

branding:
  icon: 'tag'
  color: 'blue'

inputs:
  version-level:
    description: 'Version bump level (major, minor, patch, alpha, beta, rc, dev)'
    required: true
  specific-version:
    description: 'Manually specify an exact version (e.g., 2.5.0 or 1.3.0-beta.2). Skips version bumping.'
    required: false
  current-version:
    description: 'Current version (auto-detected from git tags if not provided)'
    required: false
  tag-prefix:
    description: 'Prefix for version tags'
    required: false
    default: 'v'
  push:
    description: 'Push the tag to remote'
    required: false
    default: 'true'
  token:
    description: 'GitHub token for pushing tags'
    required: false
    default: ${{ github.token }}

outputs:
  new-version:
    description: 'The new version that was created'
    value: ${{ steps.bump.outputs.version }}
  is-prerelease:
    description: 'Whether this is a pre-release version'
    value: ${{ steps.bump.outputs.is_prerelease }}
  tag-name:
    description: 'Full tag name with prefix'
    value: ${{ steps.bump.outputs.tag_name }}

runs:
  using: composite
  steps:

  # Only run this step if no specific version is provided
    - name: Determine version
      id: bump
      if: ${{ !inputs.specific-version }}
      shell: bash
      env:
        VERSION_LEVEL: ${{ inputs.version-level }}
        CURRENT_VERSION: ${{ inputs.current-version }}
        TAG_PREFIX: ${{ inputs.tag-prefix }}
      run: bash ${{ github.action_path }}/scripts/calculate-version.sh

    # Create and push tag
    - name: Create and push tag
      shell: bash
      env:
        TAG_NAME: ${{ steps.bump.outputs.tag_name || format('{0}{1}', inputs.tag-prefix, inputs.specific-version) }}
        PUSH: ${{ inputs.push }}
        GITHUB_TOKEN: ${{ inputs.token }}
      run: bash ${{ github.action_path }}/scripts/create-tag.sh
